---
# Setup based on this script: https://get.openziti.io/ziti-cli-functions.sh

- name: Add openziti group
  ansible.builtin.group:
    name: "{{ openziti_group }}"
    gid: "{{ openziti_group_gid | default(omit) }}"
    state: present
  become: true

- name: Add openziti user
  ansible.builtin.user:
    name: "{{ openziti_user }}"
    shell: "/bin/bash"
    uid: "{{ openziti_user_uid | default(omit) }}"
    group: "{{ openziti_group }}"
  become: true

- name: Add openziti apt repository
  ansible.builtin.deb822_repository:
    name: openziti
    types: deb
    uris: https://packages.openziti.org/zitipax-openziti-deb-stable
    suites: debian
    components: main
    inrelease_path: main
    signed_by: https://get.openziti.io/tun/package-repos.gpg
  register: openziti_apt_repo

- name: Update apt index # noqa: no-handler
  when: openziti_apt_repo.changed
  ansible.builtin.apt:
    update_cache: true

- name: Ensure ziti home exist
  ansible.builtin.file:
    path: "{{ openziti_home }}"
    state: directory
    owner: "{{ openziti_user }}"
    group: "{{ openziti_group }}"
    mode: ug=rwx,o-rwx

- name: Install ziti cli
  ansible.builtin.apt:
    name: openziti

- name: Setup controller
  when: openziti_ctrl_enabled | default(false)
  ansible.builtin.include_tasks: controller.yaml
