---
- name: Setup controller
  hosts: controller

  vars:
    shibboleth_idp_domain: "idp.pxma.christians-software-schmiede.de"
    shibboleth_idp_entity_id: "someEntityId"

    openziti_ctrl_enabled: true
    openziti_router_enabled: true
    openziti_deploy_console: true
    openziti_advertised_address: "ctrl.pxma.christians-software-schmiede.de"
    openziti_router_advertised_address: "{{ openziti_advertised_address }}"
    openziti_network: "pxma"
    openziti_admin_password: "{{ lookup('env', 'ZITI_ADMIN_PW') }}"

    openziti_pki_country: "DE"
    openziti_pki_province: "BW"
    openziti_pki_locality: "Konstanz"
    openziti_pki_organisation: "HTWG Konstanz"

    nginx_remove_default_vhost: true

    certbot_admin_email: "{{ lookup('env', 'PXMA_EMAIL') }}"
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
      - nginx
    certbot_testmode: false
    certbot_create_extra_args: "{{ '' if (production | default(false) | bool ) else '--staging' }}"
    certbot_certs:
      - domains:
          - "{{ shibboleth_idp_domain }}"
          - "{{ openziti_advertised_address }}"
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "0"
    certbot_auto_renew_options: "--quiet"

  roles:
    - common
    - fail2ban
    - { role: jetty, tags: jetty }
    - { role: geerlingguy.nginx, tags: nginx }
    - { role: geerlingguy.certbot, tags: certbot }
    - { role: shibboleth_idp, tags: shibboleth }
    - { role: openziti, tags: openziti }
