---
- name: Setup EMail VM
  hosts: vms

  vars:
    openziti_router_enabled: true
    openziti_advertised_address: "ctrl.pxma.christians-software-schmiede.de"
    openziti_admin_password: "{{ lookup('env', 'ZITI_ADMIN_PW') }}"
    openziti_router_link_listener_enabled: false
    openziti_router_groups: ["pxma"]

  roles:
    - { name: common }
    - { name: openziti, tags: openziti }
    - { name: greenmail, tags: greenmail }
