---
collections:
- name: hetzner.hcloud
  version: ">=4.2.0"
- name: community.general
  version: ">=4.9.0"

roles:
  - name: geerlingguy.certbot
    version: master
  - name: geerlingguy.nginx
    version: master