---
- name: Reload Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart shibbolethidp
  ansible.builtin.systemd:
    name: "shibbolethidp"
    daemon_reload: true
    enabled: true
    state: restarted
  become: true
