---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Enable and start fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    daemon_reload: true
    state: started
    enabled: true